Pinmux device name changes
01org/CODK-M-X86-Samples pull request #34
Opened 2017-05-09 22:57 UTC by bigdinotech

-change pinmux name to be compatible with Zephyr 1.7

2017-05-12 17:18 UTC, bigdinotech commented
@eriknyquist @SidLeung please review

2017-05-17 17:59 UTC, eriknyquist approved these changes

2017-05-17 18:01 UTC, eriknyquist commented on common/arduino/variant.c
> +#define PINMUX_NAME CONFIG_PINMUX_NAME
Actually, I take my approval back.... what purpose is this define serving?

We already have "CONFIG_PINMUX_NAME", which everyone will understand instantly (it's a config file option).

Re-defining it without the CONFIG_ part is just confusing.

2017-05-17 18:02 UTC, eriknyquist requested changes
Don't see the point of re-defining CONFIG_PINMUX_NAME to a slightly different name

2017-05-17 18:03 UTC, bigdinotech commented on common/arduino/variant.c
> +#define PINMUX_NAME CONFIG_PINMUX_NAME
Just copying what Zephyr did in their example.

2017-05-17 18:29 UTC, eriknyquist commented on common/arduino/variant.c
> +#define PINMUX_NAME CONFIG_PINMUX_NAME
That doesn't mean it's required, or good. My opinion is that we should remove it.  We're not gaining any abstraction or de-cluttering any of the code by using that define. It's just an extra, unnecessary layer of indirection that requires extra effort from the reader. I feel the same about "printk-->PRINT" but that's an unrelated matter. So I won't approve that, unless you have a good reason for it that you can share?

2017-05-25 19:00 UTC, eriknyquist commented
Alright I'm must merging this, we need it

2017-05-25 19:00 UTC, merged